### ISSUE TITLE
Page load timeout on certain Incident Index page requests

### ISSUE THREAD

**Issue by chigby** [freedomofpress/pressfreedomtracker.us#1013]
Example URL: https://staging.pressfreedomtracker.us/all-incidents/?categories=10&date_lower=2020-05-25&search=protest

Brief attempts to reproduce locally yield page load times between 5 and 10 seconds, with 200+ queries to the DB recorded. The incident index page HTML view did not receive the recent performance improvements that were made to the HTML view (see #1008), so adding that in may help.  On the other hand, I'm not sure DB query counts completely explain what might be happening here. The API views we improved were performing thousands of queries (because the export is not paginated, as the HTML views are) and still managed to render in around 30 seconds. So some more investigation might be needed.

**Comment by harrislapiroff** [comment]
Thanks for the write-up here, @chigby. This would definitely be good to continue exploring.

**Comment by conorsch** [comment]
Some related work is presented in # #1014, with @harrislapiroff to review next.

**Comment by maeve-fpf** [comment]
Here's some more URLs this has happened on since the last update in infrastructure#3188:

- `/all-incidents/?categories=10&date_lower=2020-05-26&endpage=3&page=2&search=protest`
- `/blog/feed/`
- `/all-incidents/?date_lower=2020-05-26&categories=10&search=protest&endpage=3&page=3`
- `/all-incidents/feed/`

So, no surprises. I think both the feeds and the incidents should be addressed by the change in #1014 but if not let me know. Would it be useful to deploy that branch to the staging environment before merging it to `develop` to verify? That's a stopgap to having a `manage.py shell` that we could do.

**Comment by harrislapiroff** [comment]
Still getting timeouts on the incident queries, even after merging #1014. (I wasn't able to reproduce the errors at the feed endpoints, even prior to merging.) 🙁

**Comment by harrislapiroff** [comment]
It appears that #1021 resolved the timeouts at those URLs! Nice work, @chigby!

**Comment by maeve-fpf** [comment]
Checking logs - unfortunately, I see some today post-deploy. Worker restarts were logged at

- Mar 30, 2021 @ 14:56:55.494
- Mar 30, 2021 @ 14:54:39.121
- Mar 30, 2021 @ 14:53:50.116

However, I don't see a corresponding nginx message with a URL for them.

**Comment by maeve-fpf** [comment]
Found some URLs for timeouts today:

- 09:16:40 `/george-floyd-protests`
- 01:54:17 `/election-2020`
- 01:53:40 `/george-floyd-protests`

These look like a different view, so I suspect we have another problematic query involved there. (Sorry for not being able to get to enabling slow query logs on the pg side yet!)

**Comment by maeve-fpf** [comment]
Hits from Monday/Tuesday:

```
    2021/04/06 22:22:07  /george-floyd-protests/
    2021/04/06 22:22:06  /george-floyd-protests/
    2021/04/06 22:21:34  /george-floyd-protests/
    2021/04/06 22:21:30  /george-floyd-protests/
    2021/04/06 13:51:40  /george-floyd-protests/
    2021/04/06 13:51:13  /george-floyd-protests/
    2021/04/06 13:50:37  /george-floyd-protests/
    2021/04/06 13:50:34  /george-floyd-protests/
    2021/04/06 01:17:34  /election-2020/
    2021/04/06 01:17:23  /election-2020/
    2021/04/06 01:17:17  /george-floyd-protests/
    2021/04/06 01:16:52  /election-2020/
    2021/04/06 01:16:47  /george-floyd-protests/
    2021/04/06 01:16:16  /election-2020/
    2021/04/06 01:16:15  /george-floyd-protests/
    2021/04/05 19:25:19  /george-floyd-protests/
    2021/04/05 19:24:48  /george-floyd-protests/
    2021/04/05 19:24:10  /george-floyd-protests/incidents/
    2021/04/05 19:23:31  /george-floyd-protests/incidents/
    2021/04/05 19:10:19  /george-floyd-protests/
    2021/04/05 19:09:43  /george-floyd-protests/
    2021/04/05 19:08:40  /george-floyd-protests/
    2021/04/05 19:08:04  /george-floyd-protests/
    2021/04/05 19:08:00  /george-floyd-protests/
    2021/04/05 19:07:55  /george-floyd-protests/
```

The protests page takes about 20-30s to render.

**Comment by harrislapiroff** [comment]
@eloquence How would you feel about me closing this for now? The ticket is pretty vague about what it's completion criteria is, but we've made improvements to incident index page performance and now have more specific improvements to go on. (Would be happy to add general performance improvements as an epic to the board to track it as a project.)

**Comment by eloquence** [comment]
SGTM, we've got plenty of performance improvement irons in the fire now :)
